import * as vscode from 'vscode';
import { ConfigService } from '../../config/configService';
import { AiService } from '../../services/aiService';
import { GitService } from '../../services/gitService';
import { getChangesFromGitLab } from '../../services/gitlabService';
import { t } from '../../i18n';

const configService = new ConfigService();
const aiService = new AiService();

function mdToHtml(text: string): string {
  let html = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const lines = html.split('\n');
  const out: string[] = [];
  let inList = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (/^###\s/.test(trimmed)) {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push(`<h3>${trimmed.slice(3).trim()}</h3>`);
    } else if (/^##\s/.test(trimmed)) {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push(`<h2>${trimmed.slice(2).trim()}</h2>`);
    } else if (/^#\s/.test(trimmed)) {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push(`<h1>${trimmed.slice(1).trim()}</h1>`);
    } else if (/^[-*]\s/.test(trimmed)) {
      if (!inList) { out.push('<ul>'); inList = true; }
      out.push(`<li>${trimmed.slice(2).trim()}</li>`);
    } else if (/^\d+\.\s/.test(trimmed)) {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push(`<p>${trimmed}</p>`);
    } else if (trimmed === '') {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push('');
    } else {
      if (inList) { out.push('</ul>'); inList = false; }
      out.push(`<p>${line}</p>`);
    }
  }
  if (inList) out.push('</ul>');

  return out.join('\n');
}

function showReportPanel(report: string) {
  const panel = vscode.window.createWebviewPanel(
    'gitScribeReport',
    'GitScribe AI — Report',
    vscode.ViewColumn.One,
    {}
  );

  const content = mdToHtml(report);

  const html = `<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>GitScribe AI Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; line-height: 1.6; color: #d4d4d4; background: #1e1e1e; }
    h1 { color: #4fc1ff; border-bottom: 1px solid #333; padding-bottom: 8px; }
    h2 { color: #4fc1ff; margin-top: 24px; }
    h3 { color: #ce9178; }
    ul { padding-left: 20px; }
    li { margin: 4px 0; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #333; font-size: 12px; color: #888; }
    code { background: #2d2d2d; padding: 1px 4px; border-radius: 3px; font-size: 13px; }
    hr { border: none; border-top: 1px solid #333; margin: 16px 0; }
    p { margin: 8px 0; }
  </style>
</head>
<body>
  ${content}
  <div class="footer">Generated by GitScribe AI</div>
</body>
</html>`;

  panel.webview.html = html;
}

export function registerReportCommands(context: vscode.ExtensionContext): vscode.Disposable[] {
  const generateCommand = vscode.commands.registerCommand('gitScribe.generateReport', async () => {
    const config = configService.readConfig(
      vscode.workspace.workspaceFolders?.[0]?.uri.fsPath || ''
    );
    if (!config) {
      vscode.window.showErrorMessage(t('configureFirst'));
      return;
    }

    const workspaceRoot = vscode.workspace.workspaceFolders![0].uri.fsPath;
    const gitService = new GitService(workspaceRoot);

    type ModeItem = { label: string; value: string };
    const modeItems: ModeItem[] = [
      { label: `$(files) ${t('uncommitted')}`, value: 'uncommitted' },
      { label: `$(clock) ${t('today')}`, value: 'today' },
      { label: `$(calendar) ${t('dateRange')}`, value: 'date' },
      { label: `$(git-commit) ${t('betweenCommits')}`, value: 'commits' },
      { label: `$(server) ${t('gitlabCommits')}`, value: 'gitlab' },
    ];

    const picked = await vscode.window.showQuickPick(modeItems, {
      placeHolder: t('selectSource'),
    });
    if (!picked) return;

    let changes: string;

    try {
      if (picked.value === 'uncommitted') {
        changes = await gitService.getUncommittedChanges();
      } else if (picked.value === 'today') {
        const today = new Date().toISOString().split('T')[0];
        changes = await gitService.getChangesByDateRange(today, today, true);
      } else if (picked.value === 'date') {
        const fromDate = await vscode.window.showInputBox({
          prompt: t('startDate'),
          placeHolder: 'YYYY-MM-DD',
          validateInput: (v: string | undefined) => (v ? null : t('enterDate')),
        });
        if (!fromDate) return;

        const toDate = await vscode.window.showInputBox({
          prompt: t('endDate'),
          placeHolder: 'YYYY-MM-DD',
          validateInput: (v: string | undefined) => (v ? null : t('enterDate')),
        });
        if (!toDate) return;

        changes = await gitService.getChangesByDateRange(fromDate, toDate, true);
      } else if (picked.value === 'gitlab') {
        if (!config.gitlabToken) {
          vscode.window.showWarningMessage(t('gitlabTokenMissing'));
          return;
        }
        const fromDate = await vscode.window.showInputBox({
          prompt: t('startDate'),
          placeHolder: 'YYYY-MM-DD',
          validateInput: (v: string | undefined) => (v ? null : t('enterDate')),
        });
        if (!fromDate) return;

        const toDate = await vscode.window.showInputBox({
          prompt: t('endDate'),
          placeHolder: 'YYYY-MM-DD',
          validateInput: (v: string | undefined) => (v ? null : t('enterDate')),
        });
        if (!toDate) return;

        changes = await getChangesFromGitLab(
          config.gitlabUrl || 'https://gitlab.com',
          config.gitlabToken,
          gitService,
          fromDate,
          toDate,
          config.rejectUnauthorized ?? false,
          true
        );
      } else {
        const fromCommit = await vscode.window.showInputBox({
          prompt: t('startCommit'),
          placeHolder: 'e.g., abc123 or main~5',
          validateInput: (v: string | undefined) => (v ? null : t('enterCommit')),
        });
        if (!fromCommit) return;

        const toCommit = await vscode.window.showInputBox({
          prompt: t('endCommit'),
          placeHolder: 'e.g., def456 or feature/foo',
          validateInput: (v: string | undefined) => (v ? null : t('enterCommit')),
        });
        if (!toCommit) return;

        changes = await gitService.getChangesByCommits(fromCommit, toCommit);
      }
    } catch (e: any) {
      vscode.window.showErrorMessage(`Error: ${e.message}`);
      return;
    }

    if (changes.includes('Нет коммитов') || changes.includes('Нет незакоммиченных изменений')) {
      showReportPanel(changes);
      return;
    }

    vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: t('generatingReport'),
        cancellable: false,
      },
      async () => {
        try {
          const report = await aiService.generateReport(config, changes, picked.value);
          const authorName = await gitService.getGitAuthorName();
          const now = new Date();
          const dateStr = now.toLocaleDateString('ru-RU');
          const timeStr = now.toLocaleTimeString('ru-RU');
          const reportWithFooter = `${report}\n\n---\n*Report generated: ${dateStr} ${timeStr}, author: ${authorName}*`;
          showReportPanel(reportWithFooter);
        } catch (e: any) {
          vscode.window.showErrorMessage(`AI error: ${e.message}`);
        }
      }
    );
  });

  return [generateCommand];
}
